#!/bin/sh
cd $2/PowerTimeTracking.app/Contents/Resources/app/launch_processes
cp com.electron.powertimetracking.backendserver.plist ~/Library/LaunchAgents/
echo "adding PowerTimeTracking backend server to launchd..."
launchctl load ~/Library/LaunchAgents/com.electron.powertimetracking.backendserver.plist
echo "Starting PowerTimeTracking backend server..."
osascript -e 'tell app "System Events" to restart'
exit 0 # all good