#!/bin/sh
echo $USER > /tmp/env.txt
cd $2/PowerTimeTracking.app/Contents/Resources/app/launch_processes
cp com.electron.powertimetracking.backendserver.plist ~/Library/LaunchAgents/
echo "adding PowerTimeTracking backend server to launchd..."
sleep 1
sudo -u $USER launchctl unload -w ~/Library/LaunchAgents/com.electron.powertimetracking.backendserver.plist
sudo -u $USER launchctl load -w ~/Library/LaunchAgents/com.electron.powertimetracking.backendserver.plist
echo "Starting PowerTimeTracking backend server..."
# osascript -e 'tell app "System Events" to restart'
open -a PowerTimeTracking
exit 0 # all good